# Generated by Django 4.0 on 2023-07-10 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employee', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationEmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.employeemodel')),
                ('employee_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organization.organization')),
            ],
        ),
    ]
