# Generated by Django 4.0 on 2023-07-10 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Employee', '0001_initial'),
        ('Organization', '0001_initial'),
        ('OrganizationEmployeeRole', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationemployeerole',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_id', to='Employee.employeemodel'),
        ),
        migrations.AlterField(
            model_name='organizationemployeerole',
            name='employee_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='organizationemployeerole',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_id', to='Organization.organization'),
        ),
    ]
